export const OPENAI_MODEL_CATALOG = [
  {
    id: "gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    badgeEn: "Flagship",
    badgeZh: "旗舰",
    descriptionEn: "Highest capability for complex analysis and demanding reports.",
    descriptionZh: "适合最复杂的分析、推理与高要求报告。",
    speedEn: "Deliberate",
    speedZh: "较慢",
    costEn: "Highest",
    costZh: "最高",
  },
  {
    id: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    badgeEn: "Recommended",
    badgeZh: "推荐",
    descriptionEn: "Balanced intelligence, latency, and cost for everyday work.",
    descriptionZh: "兼顾质量、响应速度与成本，适合作为日常默认。",
    speedEn: "Balanced",
    speedZh: "均衡",
    costEn: "Medium",
    costZh: "中等",
  },
  {
    id: "gpt-5.6-luna",
    name: "GPT-5.6 Luna",
    badgeEn: "High volume",
    badgeZh: "高频经济",
    descriptionEn: "Fast, cost-sensitive model for frequent summaries and chat.",
    descriptionZh: "适合高频摘要、问答和成本敏感的日常任务。",
    speedEn: "Fastest",
    speedZh: "最快",
    costEn: "Lowest",
    costZh: "最低",
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5",
    badgeEn: "Previous flagship",
    badgeZh: "上一代旗舰",
    descriptionEn: "Strong professional reasoning with higher latency and cost.",
    descriptionZh: "专业推理能力强，但速度与成本压力较高。",
    speedEn: "Deliberate",
    speedZh: "较慢",
    costEn: "High",
    costZh: "较高",
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    badgeEn: "Proven quality",
    badgeZh: "成熟高质量",
    descriptionEn: "A proven option for complex professional analysis and reports.",
    descriptionZh: "适合复杂专业分析与报告的成熟高质量选择。",
    speedEn: "Standard",
    speedZh: "标准",
    costEn: "Medium-high",
    costZh: "中高",
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    badgeEn: "Efficient",
    badgeZh: "快速经济",
    descriptionEn: "Fast and economical for routine summaries and collaboration.",
    descriptionZh: "适合日常摘要、协作问答和高频常规工作。",
    speedEn: "Fast",
    speedZh: "快速",
    costEn: "Low",
    costZh: "较低",
  },
] as const;

export type OpenAiModelId = (typeof OPENAI_MODEL_CATALOG)[number]["id"];

export function isOpenAiModelId(value: string): value is OpenAiModelId {
  return OPENAI_MODEL_CATALOG.some((model) => model.id === value);
}
